linters-settings:
  dupl:
    threshold: 100
  lll:
    line-length: 80
  varnamelen:
    ignore-names:
      - v
      - ok
  gci:
    local-prefixes: github.com/maranqz/go-immutable

linters:
  enable-all: true
  disable:
    - maligned
    - testpackage
    - deadcode
    - golint
    - scopelint
    - varcheck
    - structcheck
    - nosnakecase
    - exhaustivestruct
    - ifshort
    - exhaustruct
    - depguard
    - interfacer
    - godox # TODO activate
    - forbidigo # TODO activate
    - paralleltest  # TODO activate

run:
  skip-dirs:
    - testdata

issues:
  exclude-rules:
    - path: lint_test
      linters:
        - varnamelen
    - linters:
        - lll
      source: "^(?: |\t)*// "
    - linters:
        - lll
      source: "[`\"'].*[`\"']"
    - linters:
        - godot
        - lll
      source: "// ?TODO "